// App template id and infrastructure version this scaffold ships with.
//
// The product reads these values from the generated manifest
// (`app.template_id` and `app.template_version`) to detect when an existing
// app can be upgraded on the matching template track. Do not edit this file
// in an app project: it is part of the template's infra layer and is
// replaced wholesale during a template upgrade.
export const KYLON_APP_TEMPLATE_ID = "general-website";
export const KYLON_APP_TEMPLATE_VERSION = "1.2.7";
